name: Um pipeline para meu ello world
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekcout@v1
      - uses: ./action-a
          with:
            MY_NAME: "Dayvson Silva"